# Generated by Django 4.2.3 on 2023-10-02 04:29

import autoslug.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_doctor_slug_alter_patient_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='slug',
            field=autoslug.fields.AutoSlugField(blank=True, editable=False, null=True, populate_from='user__name', unique=True),
        ),
    ]
