# Generated by Django 4.2.3 on 2023-10-02 05:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_doctor_slug_alter_patient_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='slug',
        ),
    ]
